
# contenedores

services:
  mi-mongo-dc:

   # imagen desde la que inicia
    image: mongo

    # -p
    ports:
      - 27017:27017

    # --name
    container_name: mi-mongo-dc

    # --mount source:target
    volumes:
      - mi-mongo-vol-dc:/data/db

    # --network
    networks:
      mi-mongo-red-dc:

    # -i
    stdin_open:  true 

    # -t
    tty:  true

  mi-mongo-express-dc:

    image: mongo-express

    # --name    
    container_name: mi-mongo-express-dc

    # -p    
    ports:
      - 8081:8081

    # --network  
    networks:
      mi-mongo-red-dc:

    # -e    
    environment:
      - ME_CONFIG_MONGODB_SERVER=mi-mongo-dc
    stdin_open:  true # -i
    tty:  true # -t

# network
networks:
  mi-mongo-red-dc:
    ipam:
      driver:  default
      config:
        # --subnet
        - subnet:  172.100.0.0/16

# volume
volumes:
  mi-mongo-vol-dc:


